export const AUTH_FETCH_DATA = 'AUTH/FETCH_DATA'
export const GAME_FETCH_DATA = 'GAME/FETCH_DATA'

export const APP_HIDE_LOADER = 'APP/HIDE_PRELOADER'
export const GAME_HIDE_LOADER = 'GAME/HIDE_PRELOADER'

export const GAME_SETTINGS_TIMER_CHANGE = 'GAME/SETTINGS/TIMER_CHANGE'
export const GAME_SETTINGS_WILDCARD_TOGGLE = 'GAME/SETTINGS/WILDCARD_CHANGE'

export const GAME_ACTIONS_STREAK_CHANGE = 'GAME/ACTIONS/STREAK_CHANGE'
export const GAME_ACTIONS_STREAK_INCREMENT = 'GAME/ACTIONS/STREAK_INCREMENT'
export const GAME_ACTIONS_STREAK_RESET = 'GAME/ACTIONS/STREAK_RESET'
export const GAME_ACTIONS_TIMER_STATUS_TOGGLE = 'GAME/ACTIONS/TIMER_START'
export const GAME_ACTIONS_TIMER_END_TIME_CHANGE = 'GAME/ACTIONS/TIMER_END_TIME_CHANGE'
export const GAME_ACTIONS_TIMER_MS_LEFT_CHANGE = 'GAME/ACTIONS/TIMER_MS_LEFT_CHANGE'
export const GAME_ACTIONS_WILDCARD_TOGGLE = 'GAME/ACTIONS/WILDCARD_CHANGE'

export const GAME_PLAYERS_SELECT = 'GAME/PLAYERS/SELECT'
export const GAME_PLAYERS_REMOVE = 'GAME/PLAYERS/REMOVE'
export const GAME_PLAYERS_SKIP_CURRENT_TOGGLE = 'GAME/PLAYERS/SKIP_CURRENT_TOGGLE'
export const GAME_PLAYERS_ADD = 'GAME/PLAYERS/ADD'
